# Generated by Django 5.0 on 2024-01-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_projects_nog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalidad',
            name='uploadedFile',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='uploadedFile',
            field=models.FileField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploadedFile',
            field=models.FileField(null=True, upload_to='Videos/'),
        ),
    ]
